version: "3.7"

networks:
  mojaloop-net:
    name: mojaloop-net

services:
  als-static-oracle-svc:
    container_name: co_als-static-oracle-svc
    image: mojaloop/als-static-oracle-svc:local
    build:
      context: .
      cache_from:
        - mojaloop/als-static-oracle-svc:local
    ports:
      - "3000:3000"
    networks:
      - mojaloop-net
    healthcheck:
      test: ["CMD", "sh", "-c" ,"apk --no-cache add curl", ";", "curl", "http://localhost:3008/health"]
      timeout: 20s
      retries: 10
      interval: 30s
    user: root

